# Конфигурационный файл для плагина AntiCheatGpt2

# Настройки для проверки на спидхак
speedcheck:
  # Максимальная допустимая скорость игрока на земле (в блоках за тик)
  max-speed: 0.25

# Настройки для проверки на NoSlow
noslowcheck:
  # Максимальная допустимая скорость для игроков, использующих предметы (например, лук или еда)
  max-speed-with-item: 0.25

# Настройки для проверки на флай
flycheck:
  # Максимальная допустимая вертикальная скорость игрока
  max-vertical-speed: 0.1

# Настройки для проверки на стрейф
strafingcheck:
  # Максимальный угол для нормального стрейфа игрока
  max-strafe-angle: 1.0

# Общее количество предупреждений (алертов) для игрока
alerts:
  # Количество алертов, после которого игрок будет временно заблокирован (например, 3 алерта)
  max-alerts-before-ban: 3

# Настройки для логирования
logging:
  # Включить/выключить логирование в консоль
  log-in-console: true
  # Включить/выключить логирование на игрока
  log-to-player: true

# Сообщения для оповещений
messages:
  speed-alert: "Обнаружен спидхак! Игрок двигается слишком быстро."
  noslow-alert: "Обнаружено использование NoSlow! Игрок двигается слишком быстро с предметом."
  fly-alert: "Обнаружен флай! Игрок движется слишком быстро вертикально."
  strafing-alert: "Обнаружен стрейф с нечестной манипуляцией направления."
  alerts-info: "Вы получили %alerts% алертов."
  cleared-alerts: "Ваши алерты были очищены."
  plugin-info: "Плагин AntiCheatGpt2 активен! Доступные команды: /anticheat, /anticheat clear, /anticheat info."
